paths:
  /api/products:
    get:
      summary: Endpoint para obtener todos los productos
      tags:
        - Productos
      responses:
        "200":
          description: Se obtuvieron correctamente todos los productos
        "401":
          description: No tienes permisos para esta ruta
        "500":
          description: Se produjo un error interno en el servidor

    post:
      summary: Endpoint para crear un nuevo producto
      tags:
        - Productos
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  required: true
                description:
                  type: string
                  required: true
                price:
                  type: number
                  required: true
                thumbnail:
                  type: string
                category:
                  type: string
                  required: true
                  enum: ["Zapatilla", "Pantalon", "Remera", "Campera"]
      responses:
        "201":
          description: Se creó correctamente el nuevo producto
        "401":
          description: No tienes permisos para esta ruta
        "400":
          description: Los datos ingresados no son válidos
        "500":
          description: Se produjo un error interno en el servidor

  /api/products/{pid}:
    get:
      summary: Endpoint para obtener productos por id
      tags:
       - Productos
      parameters:
        -name: pid
        -in: path
        -description: Id del producto
        -required: true
        -type: string
        -example: uejdjaiwkfjal20193
      responses:
        "200":
          description: Se obtuvo correctamente el producto
        "401":
          description: No tienes permisos para esta ruta
        "500":
          description: Se produjo un error en el servidor
        "404":
          description: El producto no existe

    put:
      summary: Actualizar un producto
      tags:
        - Productos
      parameters:
        - name: pid
          in: path
          description: ID del producto
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  required: true
                description:
                  type: string
                  required: true
                price:
                  type: number
                  required: true
                thumbnail:
                  type: string
                category:
                  type: string
                  required: true
                  enum: ["Zapatilla", "Pantalon", "Remera", "Campera"]
      responses:
        "200":
          description: El producto se actualizó correctamente
        "401":
          description: No tienes permisos para esta ruta
        "400":
          description: Los datos ingresados no son válidos
        "500":
          description: Se produjo un error interno en el servidor
        "404":
          description: El producto no existe

    delete:
      summary: Eliminar un producto
      tags:
        - Productos
      parameters:
        - name: pid
          in: path
          description: ID del producto
          required: true
          schema:
            type: string
      responses:
        "200":
          description: El producto se eliminó correctamente
        "401":
          description: No tienes permisos para esta ruta
        "500":
          description: Se produjo un error en el servidor
        "404":
          description: El producto no existe


components:
  schemas:
    Producto:
      type: object
      properties: 
        _id:
          type: ObjectId
          description: id del usuario generado por MongoDB
        title:
          type: String
          description: Titulo del producto
        description:
          type: String
          description: Descripcion del producto
        price:
          type: Number
          description: Precio del producto
        thumbnail:
          type: String
          description: Url de la imagen
        code:
          type: String
          description: Codigo del producto
        stock:
          type: Number
          description: Stock disponible del producto
        category:
          type: String
          description: Categoria del producto a
      example:
        _id: 123456789
        title: pantalon
        description: Pantalon de jean negro
        price: 24000
        thumbnail: www.asdasd.com
        code: nkdha30
        stock: 50
        category: Zapatilla

  